# Python 3.11 ベースの公式イメージを使用
FROM python:3.11-slim

# 必要なパッケージと作業ディレクトリの設定
WORKDIR /app

# アプリケーションコードのコピー（ビルド対象がローカルにある場合）
COPY . .

# Pythonライブラリのインストール（Django, pyVmomiなど）
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
